# name of your application
APPLICATION = trace
include ../Makefile.tests_common

USEMODULE += trace

BOARD_WHITELIST := native native64

TEST_ON_CI_WHITELIST += all

include $(RIOTBASE)/Makefile.include
