include ../Makefile.tests_common

BOARD_WHITELIST := native native64

USEMODULE += gnrc_ipv6
USEMODULE += gnrc_sock_udp
USEMODULE += oonf_common
USEMODULE += oonf_rfc5444
USEPKG += oonf_api

include $(RIOTBASE)/Makefile.include
