ifeq ($(shell uname -m),x86_64)
  export CFLAGS += -m32
  export LINKFLAGS += -m32
endif

ifeq ($(shell uname -s),FreeBSD)
  ifeq ($(shell uname -m),amd64)
    export CFLAGS += -m32 -DCOMPAT_32BIT -B/usr/lib32
    export LINKFLAGS += -m32 -DCOMPAT_32BIT -L/usr/lib32 -B/usr/lib32
  endif
endif

include $(RIOTBOARD)/common/native-base/Makefile.include
